### ISSUE TITLE
UX - Keyboard shortcuts

### ISSUE THREAD

**Issue by dllndv** [PracticeJavaScript/practicejavascript.com#7]
I think we could use some keyboard shortcuts, such as shift+enter to go to the next problem, and a different shortcut for the shuffle button. Maybe a shortcut to copy their whole solution in case they wanted to make a gist of all the answers. Just a goal to make the app completely usable without touching the mouse.

**Comment by spacerockzero** [comment]
Yes, I've been frustrated by having to leave the keyboard when i'm on a roll, too. great idea!

**Comment by spacerockzero** [comment]
Research:

SUBMIT keybinding:

- es6Katas: cmd-S to re-test
- codewars: cmd-S to re-test, cmd-return to submit final and move on
- freeCodeCamp: cmd-return/ctrl-return to re-test. If passed, another cmd-return goes to next problem.

**Comment by spacerockzero** [comment]
Could also automatically move to next problem if the tests all pass

**Comment by dllndv** [comment]
maybe a simple button slides in at the bottom of the code window, congratulating the user and then just says, "hit enter for next problem". Moving them automatically to the next problem might make them wonder if something's broken.

**Comment by spacerockzero** [comment]
I have a PR for the next/prev keybindings ready here: https://github.com/PracticeJavaScript/practicejavascript.com/pull/35
It could use more browser testing on non-mac things.

**Comment by spacerockzero** [comment]
merged.
